# Generated by Django 5.0.2 on 2024-03-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_academico', '0002_curso_departamento_alter_professor_departamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='coordenador',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='duracao',
        ),
        migrations.AddField(
            model_name='curso',
            name='nota',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='situacao',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
