# Generated by Django 5.0.2 on 2024-03-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_academico', '0003_remove_curso_coordenador_remove_curso_duracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='data_contratacao',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
